### ISSUE TITLE
Trip proposal 

### ISSUE THREAD

**Issue by Loreen17** [lotus-coding-school/master-reference#7]
Here is the official trip plan:
Where? Hermon
What? one day trip
When? 8/7/2019
Why? celebrating finishing the bootcamp

issue #6 

:dancer:

**Comment by Noorb7188** [comment]
id rather go to Eilat :hear_no_evil:

**Comment by sabeel29** [comment]
:+1: 
:)

**Comment by amanhalabyar** [comment]
:tada:

**Comment by sara141** [comment]
🏇

**Comment by Loreen17** [comment]
great lets have a meeting :100:
