### ISSUE TITLE
Trip proposal failed

### ISSUE THREAD

**Issue by Loreen17** [lotus-coding-school/master-reference#8]
Two people didn't agree because it's cold in the Hermon @enasskmal ,
and @Jasmineb2011   said the there won't be snow in August.

issue #7 #6 

:disappointed:

**Comment by MynahMarie** [comment]
Awww... too bad... can I close this issue then?

**Comment by Loreen17** [comment]
sure you can close it

**Comment by MynahMarie** [comment]
👍
